[build]
  command = "npm run build"
  functions = "functions-src"
  publish = "public"

[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"